export const REQUEST_CONTENT_LIST = 'REQUEST_CONTENT_LIST'
export const GET_CONTENT_LIST = 'GET_CONTENT_LIST'
export const GET_CONTENT_LIST_FAILURE = 'GET_CONTENT_LIST_FAILURE'

export const GET_MYHELLO = 'GET_MYHELLO'
export const GET_MYHELLO_FAILURE = 'GET_MYHELLO_FAILURE'
export const CLEAR_MYHELLO = 'CLEAR_MYHELLO'

export const REQUEST_MEDICINE_LIST = 'REQUEST_MEDICINE_LIST'
export const GET_MEDICINE_LIST = 'GET_MEDICINE_LIST'
export const GET_MEDICINE_LIST_FAILURE = 'GET_MEDICINE_LIST_FAILURE'

export const GET_MEDICINEDATA = 'GET_MEDICINEDATA'
export const GET_MEDICINEDATA_FAILURE = 'GET_MEDICINEDATA_FAILURE'
export const CLEAR_MEDICINEDATA = 'CLEAR_MEDICINEDATA'

